export const replacementRulesMap: Record<string, string> = {
  'test=$name': 'foo[bar=$name] .qux',

  'grid': 'app-grid',
  'grid=$name': 'app-grid[entitylabel=$name]',
  'grid-header-column': '.ag-header-cell',
  'grid-titles': '.ag-header-row-column',
  'grid-titles-column': '.ag-header-row-column .ag-header-cell',
  'grid-filters': '[ref="eHeaderViewport"] .ag-header-row-floating-filter',
  'grid-filters-column': '[ref="eHeaderViewport"] .ag-header-row-floating-filter .ag-header-cell',
  'grid-pinned-left': '[ref="eLeftContainer"]',
  'grid-rows': '[ref="eCenterColsClipper"]',
  'grid-pinned-right': '[ref="eRightContainer"]',
  'grid-floating-bottom': '[ref="eBottom"]',
  'grid-row': '.ag-row',
  'grid-cell': '.ag-cell',
  'grid-overlay': '[ref="overlayWrapper"]',

  'datepicker': 'ngb-datepicker',
  'datepicker-navigation': 'ngb-datepicker-navigation',
  'datepicker-month-selector': 'ngb-datepicker-navigation-select select:nth-child(1)',
  'datepicker-year-selector': 'ngb-datepicker-navigation-select select:nth-child(2)',
  'datepicker-prev-arrow': 'ngb-datepicker-navigation .ngb-dp-arrow:first-child button',
  'datepicker-next-arrow': 'ngb-datepicker-navigation .ngb-dp-arrow:last-child button',
  'datepicker-month-days': '.ngb-datepicker-month',
  'datepicker-day': '.ngb-dp-day',

  'quill': 'quill-editor',
  'quill-picker-item': '.ql-picker-item',
  'quill-toolbar': '.ql-toolbar',
  'quill-format-bold': '.ql-formats .ql-bold',
  'quill-format-italic': '.ql-formats .ql-italic',
  'quill-format-underline': '.ql-formats .ql-underline',
  'quill-format-strike': '.ql-formats .ql-strike',
  'quill-format-ordered-list': '.ql-formats .ql-list[value="ordered"]',
  'quill-format-bullet-list': '.ql-formats .ql-list[value="bullet"]',
  'quill-format-sub': '.ql-formats .ql-script[value="sub"]',
  'quill-format-super': '.ql-formats .ql-script[value="super"]',
  'quill-format-color': '.ql-formats .ql-color',
  'quill-format-align': '.ql-formats .ql-align',
  'quill-format-align-center': '.ql-picker-options .ql-picker-item[data-value="center"]',
  'quill-format-align-right': '.ql-picker-options .ql-picker-item[data-value="right"]',
  'quill-format-align-justify': '.ql-picker-options .ql-picker-item[data-value="justify"]',
  'quill-format-clean': '.ql-formats .ql-clean',
  'quill-format-link': '.ql-formats .ql-link',
  'quill-content': '.ql-editor',
  'quill-tooltip': '.ql-tooltip',

  'toast': 'ngx-toastr',
  'toast-success': 'ngx-toastr.toast-success',
  'toast-warning': 'ngx-toastr.toast-warning',
  'toast-error': 'ngx-toastr.toast-danger',
  'toast-info': 'ngx-toastr.toast-info',
  'toast-title': '.toast-title',
  'toast-message': '.toast-message',
}

