export const environment = {
  production: true,
  real_production: false,
  showLogs: false,
  isUat: false,
  api_url: 'https://ac-api.uat-demo.s3betaplatform.com/api',
  help_url: 'https://ac-api.uat-demo.s3betaplatform.com/help',
  hangfire_url: 'https://ac-api.uat-demo.s3betaplatform.com/jobs',
  user_role_type_id: 2,
  sts_server: 'https://ac-login.uat-demo.s3betaplatform.com',
  pusher_key: 'f85fea3de3bd17a827f1',
  pusher_cluster: 'mt1',
  lpm_url: 'https://lpm.uat-demo.s3betaplatform.com',
  sentry_dsn: 'https://e514877a0f0f4b6dbd34c4f4e23e942a@o475152.ingest.sentry.io/5512994',
  sentry_environment: 'uat-demo',
  sentry_feedback: false,
  version: '4.6',
  gtm: null,
  master_org_name: 'ARCHER Systems, LLC',
};
