export enum DocumentType {
  EVResponse = 1,
  StatusReport = 7,
  LienLetter = 8,
  ElectionForm = 16,
  ClosingStatement = 37,
  FeeAndExpenseTemplate = 46,
  AdvancedPaymentInstructions = 453,
  PaymentRequestValidation = 461,
  RemittanceDetailsTemplate = 454,
  RemittanceDetailsTemplatePLRP = 455,
  InputDocument = 462,
  ResultDocument = 463,
  OtherClients = 19,
  CommunicationEmailAttachment = 467,
  CommunicationEmailMessage = 199,
  WireInstruction = 473,
  DocusignIntegrationTemplate = 474,
  PaymentCoversheetTemplate = 475,
  DisbursementWorkSheet = 452,
  DeficiencyReport = 114,
}
