export enum FileImportTemplateTypes {
  Intake = 1,
  CondensedDisbursementWorksheet = 3,
  DisbursementGroups = 4,
  LedgerArcherFees = 7,
  LedgerLienDataFees = 23,
  GrossAllocation = 24,
  GTFMDW = 25,
  DetailedDisbursementWorksheet = 26,
  FirmFeeAndExpense = 27,
  ClientOrganizationEntityAccess = 30,
  SpecialPaymentInstructions = 204,
  ProbateClaimantImport = 207,
  NewDetailedDisbursementWorksheet = 214,
  NewGTFMDW = 215,
  SimpleGeneralLedger = 216,
  ClientExternalIdentifiers = 217,
  DisbursementGroupAllocation = 218,
}

export const TempaltesWithoutConfigStage: FileImportTemplateTypes[] = [
  FileImportTemplateTypes.ClientOrganizationEntityAccess,
  FileImportTemplateTypes.SpecialPaymentInstructions,
  FileImportTemplateTypes.ProbateClaimantImport,
  FileImportTemplateTypes.GrossAllocation,
  FileImportTemplateTypes.GTFMDW,
  FileImportTemplateTypes.DetailedDisbursementWorksheet,
  FileImportTemplateTypes.NewDetailedDisbursementWorksheet,
  FileImportTemplateTypes.NewGTFMDW,
  FileImportTemplateTypes.LedgerLienDataFees,
  FileImportTemplateTypes.SimpleGeneralLedger,
  FileImportTemplateTypes.ClientExternalIdentifiers,
  FileImportTemplateTypes.FirmFeeAndExpense,
  FileImportTemplateTypes.DisbursementGroupAllocation,
];
