export enum SearchTypeEnum {
  NotEqual = 'notEqual',
  Equals = 'equals',
  Contains = 'contains',
  NotContains = 'notContains',
  StartsWith = 'startsWith',
  EndsWith = 'endsWith',
  LessThan = 'lessThan',
  LessThanOrEqual = 'lessThanOrEqual',
  GreaterThan = 'greaterThan',
  GreaterThanOrEqual = 'greaterThanOrEqual',
  InRange = 'inRange',
  InRangeDays = 'inRangeDays',
  InRangeMonths = 'inRangeMonths',
  GreaterThanDays = 'greaterThanDays',
  GreaterThanMonths = 'greaterThanMonths',
  LessThanDays = 'lessThanDays',
  LessThanMonths = 'lessThanMonths',
}
