export enum KeyCodes {
  Backspace = 'Backspace',
  Tab = 'Tab',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  Delete = 'Delete',
  WindowKeyLeft = 'MetaLeft',
  WindowKeyRight = 'MetaRight',
  WindowsMenu = 'ContextMenu',
  Comma = 'Comma',
  Space = 'Space',
  F2 = 'F2',
  Enter = 'Enter',
  NumpadEnter = 'NumpadEnter',
  Escape = 'Escape',
  ShiftLeft = 'ShiftLeft',
  ShiftRight = 'ShiftRight',
  RCtrl = 'ControlRight',
  LCtrl = 'ControlLeft',
  KeyA = 'KeyA',
  Home = 'Home',
  End = 'End',
}
