export enum StopPaymentRequestStatusEnum {
  Review = 155,
  WaitingPeriod = 156,
  ReadyToPay = 157,
  Completed = 158,
  Rejected = 159,
  InquiryAddlInfoRequested = 160,
  PendingAPUpdates = 163,
  APUpdatesComplete = 164,
  PendingQC = 165,
  QCApproved = 166,
  QCDeclined = 167,
  PendingSmartPayableReview = 168,
  SmartPayableReviewApproved = 169,
  SmartPayableReviewDeclined = 170,
  RejectedWrongCheck = 171,
}

export enum StopPaymentStatusForBatchUpdateEnum {
  'Review' = StopPaymentRequestStatusEnum.Review,
  'Pending - AP Updates' = StopPaymentRequestStatusEnum.PendingAPUpdates,
  'AP Updates Complete' = StopPaymentRequestStatusEnum.APUpdatesComplete,
  'Waiting Period' = StopPaymentRequestStatusEnum.WaitingPeriod,
  'Ready to Pay' = StopPaymentRequestStatusEnum.ReadyToPay,
  'Pending - QC' = StopPaymentRequestStatusEnum.PendingQC,
  'QC - Approved' = StopPaymentRequestStatusEnum.QCApproved,
  'QC - Declined' = StopPaymentRequestStatusEnum.QCDeclined,
  'Pending -  Smart Payable Review' = StopPaymentRequestStatusEnum.PendingSmartPayableReview,
  'Smart Payable Review - Approved' = StopPaymentRequestStatusEnum.SmartPayableReviewApproved,
  'Smart Payable Review - Declined' = StopPaymentRequestStatusEnum.SmartPayableReviewDeclined,
  'Completed' = StopPaymentRequestStatusEnum.Completed,
  'Inquiry - Add\'l Info Requested' = StopPaymentRequestStatusEnum.InquiryAddlInfoRequested,
  'Rejected' = StopPaymentRequestStatusEnum.Rejected,
  'Rejected - Wrong Check' = StopPaymentRequestStatusEnum.RejectedWrongCheck,
}
