export enum PaymentItemType {
  Lien = 1,
  LienInterest = 2,
  AdminFee = 3,
  Claimant = 4,
  ClaimantProvision = 5,
  ClaimantDisbursement = 24,
  HoldbackDisbursement = 25,
  EIFDisbursement = 26,
  PrimaryFirmFees = 12,
  AttorneyFees = 13,
  AttorneyExpenses = 14,
  Advance = 17,
  Vendor = 15,
  TaxPayment = 16,
  ArcherFees = 19,
  DeductionsTrusteeAdminFees = 27,
  MDL = 22,
  CBF = 23,
  ReferringFirmFees = 30,
  SettlementCounselFees = 31,
  PrimaryFirmExpenses = 32,
  ReferringFirmExpenses = 33,
  SettlementCounselExpenses = 34,
}
