export enum SettlementFinancialHeadersEnum {
  MDLCBF = 'MDL / CBF Payment',
  AttorneyFees = 'Attorney Fees',
  AttorneyExpenses = 'Attorney Expenses',
  MedicalLiens = 'Medical Liens',
  LienHoldbacks = 'Lien Holdbacks',
  ThirdPartyExpenses = '3rd Party Expenses',
  ARCHERFees = 'ARCHER Fees',
  FeeHoldbacks = 'Fee Holdbacks',
  OtherFees = 'Other Fees',
  ClaimantPayments = 'Claimant Payments',
  LienRefunds = 'Lien Refunds',
  SpecialMaster = 'Special Master',
  Taxes = 'Taxes',
  OtherHoldbacks = 'Other Holdbacks',
  OtherRefunds = 'Other Refunds',
  SettlementAmount = 'Settlement Amount',
  TotalClaimantAllocations = 'Total Claimant Allocations',
  TotalInterest = 'Total Interest',
  TotalDeposits = 'Total Deposits',
  QSFBalance = 'QSF Balance',
}

export enum ChartedSettlementFinancialHeadersEnum {
  MDLCBF = SettlementFinancialHeadersEnum.MDLCBF,
  AttorneyFees = SettlementFinancialHeadersEnum.AttorneyFees,
  AttorneyExpenses = SettlementFinancialHeadersEnum.AttorneyExpenses,
  MedicalLiens = SettlementFinancialHeadersEnum.MedicalLiens,
  LienHoldbacks = SettlementFinancialHeadersEnum.LienHoldbacks,
  ThirdPartyExpenses = SettlementFinancialHeadersEnum.ThirdPartyExpenses,
  ARCHERFees = SettlementFinancialHeadersEnum.ARCHERFees,
  FeeHoldbacks = SettlementFinancialHeadersEnum.FeeHoldbacks,
  OtherFees = SettlementFinancialHeadersEnum.OtherFees,
  ClaimantPayments = SettlementFinancialHeadersEnum.ClaimantPayments,
  LienRefunds = SettlementFinancialHeadersEnum.LienRefunds,
  SpecialMaster = SettlementFinancialHeadersEnum.SpecialMaster,
  Taxes = SettlementFinancialHeadersEnum.Taxes,
  OtherHoldbacks = SettlementFinancialHeadersEnum.OtherHoldbacks,
  OtherRefunds = SettlementFinancialHeadersEnum.OtherRefunds,
}
